FROM nginx:alpine

ENV webroot /usr/share/nginx/html

COPY root $webroot/
COPY chals/Napkin.pdf $webroot/
COPY chals/SquidwardSecret.png $webroot/
COPY chals/KrustyKrabRegister.png $webroot/
COPY chals/receipt.png $webroot/
