FROM nginx:alpine

COPY memorial.png /usr/share/nginx/html/
COPY edited_photo.png /usr/share/nginx/html/
COPY chal_img.jpeg /usr/share/nginx/html/
COPY chal-img.png /usr/share/nginx/html/
COPY _robots.png /usr/share/nginx/html/
COPY chal.png /usr/share/nginx/html/
COPY challenge.docx /usr/share/nginx/html/
COPY challenge.docx /usr/share/nginx/html/