FROM nginx:alpine

COPY chance.jpg /usr/share/nginx/html/
RUN true
COPY edited_photo.png /usr/share/nginx/html/
RUN true
COPY chal-img.png /usr/share/nginx/html/
RUN true
COPY _robots.png /usr/share/nginx/html/
RUN true
COPY chal.png /usr/share/nginx/html/
RUN true
COPY evidence.zip /usr/share/nginx/html/
RUN true
COPY output.wav /usr/share/nginx/html/
RUN true
COPY login.pcap /usr/share/nginx/html/
RUN true
COPY edited_photo.png /usr/share/nginx/html/
RUN true
COPY chrome.tar.gz /usr/share/nginx/html/
RUN true
COPY chal.zip /usr/share/nginx/html/
RUN true
COPY chance.jpg /usr/share/nginx/html/
RUN true
COPY edited_photo.png /usr/share/nginx/html/
RUN true
COPY _robots.png /usr/share/nginx/html/
RUN true
COPY chal.png /usr/share/nginx/html/
RUN true
COPY chal-img.png /usr/share/nginx/html/
RUN true
COPY latke_recipe.docx /usr/share/nginx/html/
RUN true
COPY access.log /usr/share/nginx/html/
RUN true
COPY latke_recipe.docx /usr/share/nginx/html/
RUN true
COPY access.log /usr/share/nginx/html/
RUN true
COPY latke_recipe.docx /usr/share/nginx/html/
RUN true
COPY access.log /usr/share/nginx/html/
RUN true
COPY latke_recipe.docx /usr/share/nginx/html/
RUN true
COPY access.log /usr/share/nginx/html/
RUN true
COPY latke_recipe.docx /usr/share/nginx/html/
RUN true
COPY access.log /usr/share/nginx/html/
RUN true
COPY vacation.jpg /usr/share/nginx/html/
RUN true
COPY keylog.pcap /usr/share/nginx/html/
RUN true
COPY keylog.pcap /usr/share/nginx/html/
RUN true
COPY vacation.jpg /usr/share/nginx/html/
RUN true